apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: my-app
