--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: application
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  #volumeName: example-pv